spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&useSSL=false
    username: root
    password: zwz520
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    # 打印sql语句
    show-sql: true
    open-in-view: true
#    hibernate:
#      ddl-auto: update
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  data:
    elasticsearch:
      # 超时时间
      properties:
        transport:
          tcp:
            connect_timeout: 120s
      cluster-name: blog
      cluster-nodes: localhost:9300
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  tomcat:
    uri-encoding: UTF-8
# 文件服务器地址
file:
  server:
    url: http://localhost:8081/file/upload
